datadog_api_key: "{{ dd_key_vault }}"
datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: "http://localhost:8080"
        timeout: 5
        method: GET