- name: Setup Infrastructure
  hosts: localhost
  become: yes
  vars:
    terraform_dir: "{{ playbook_dir }}/../terraform"
  roles:
    - infrastructure
  tags: infrastructure

- name: Deploy
  hosts: all
  become: yes
  roles:
    - deploy
  tags: deploy

- name: Monitoring
  hosts: all
  become: yes
  roles:
    - monitoring
  tags: monitoring